import smtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

SMTP_EMAIL = os.getenv("SMTP_EMAIL")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")
HR_EMAIL = os.getenv("HR_EMAIL")

def send_hr_email(name: str, role: str, experience: str, tech_stack: str, checklist: list) -> str:
    """HR ko structured completion email bhejo"""

    completed = [t for t in checklist if t["is_completed"]]
    pending = [t for t in checklist if not t["is_completed"]]
    total = len(checklist)
    done = len(completed)
    score = int((done / total) * 100) if total > 0 else 0

    completed_rows = "".join([
        f"<tr><td style='padding:8px;border-bottom:1px solid #eee;'>✅ {t['task_name']}</td>"
        f"<td style='padding:8px;border-bottom:1px solid #eee;color:green;'>Completed</td></tr>"
        for t in completed
    ])

    pending_rows = "".join([
        f"<tr><td style='padding:8px;border-bottom:1px solid #eee;'>⏳ {t['task_name']}</td>"
        f"<td style='padding:8px;border-bottom:1px solid #eee;color:orange;'>Pending</td></tr>"
        for t in pending
    ]) if pending else "<tr><td colspan='2' style='padding:8px;color:green;'>All tasks completed!</td></tr>"

    html = f"""
    <html>
    <body style="font-family: Arial, sans-serif; max-width: 600px; margin: auto;">
        <div style="background: #6366F1; padding: 24px; border-radius: 8px 8px 0 0;">
            <h1 style="color: white; margin: 0;">Onboarding Completion Report</h1>
        </div>
        
        <div style="background: #f9f9f9; padding: 24px; border: 1px solid #eee;">
            <h2 style="color: #333;">Employee Details</h2>
            <table style="width:100%; border-collapse: collapse;">
                <tr>
                    <td style="padding: 8px; font-weight: bold; color: #666;">Name</td>
                    <td style="padding: 8px;">{name}</td>
                </tr>
                <tr>
                    <td style="padding: 8px; font-weight: bold; color: #666;">Role</td>
                    <td style="padding: 8px;">{experience.capitalize()} {role.capitalize()}</td>
                </tr>
                <tr>
                    <td style="padding: 8px; font-weight: bold; color: #666;">Tech Stack</td>
                    <td style="padding: 8px;">{tech_stack.capitalize()}</td>
                </tr>
                <tr>
                    <td style="padding: 8px; font-weight: bold; color: #666;">Completion</td>
                    <td style="padding: 8px;">
                        <span style="background: #6366F1; color: white; padding: 4px 12px; border-radius: 20px;">
                            {score}% ({done}/{total} tasks)
                        </span>
                    </td>
                </tr>
                <tr>
                    <td style="padding: 8px; font-weight: bold; color: #666;">Timestamp</td>
                    <td style="padding: 8px;">{datetime.now().strftime('%d %B %Y, %H:%M IST')}</td>
                </tr>
            </table>

            <h2 style="color: #333; margin-top: 24px;">Onboarding Checklist</h2>
            <table style="width:100%; border-collapse: collapse; border: 1px solid #eee;">
                <thead>
                    <tr style="background: #6366F1; color: white;">
                        <th style="padding: 10px; text-align: left;">Task</th>
                        <th style="padding: 10px; text-align: left;">Status</th>
                    </tr>
                </thead>
                <tbody>
                    {completed_rows}
                    {pending_rows}
                </tbody>
            </table>
        </div>

        <div style="background: #6366F1; padding: 16px; border-radius: 0 0 8px 8px; text-align: center;">
            <p style="color: white; margin: 0; font-size: 13px;">
                Generated by Onboarding Agent • {datetime.now().strftime('%d %b %Y')}
            </p>
        </div>
    </body>
    </html>
    """

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Onboarding Complete — {name} ({experience.capitalize()} {role.capitalize()})"
    msg["From"] = SMTP_EMAIL
    msg["To"] = HR_EMAIL
    msg.attach(MIMEText(html, "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(SMTP_EMAIL, SMTP_PASSWORD)
            server.sendmail(SMTP_EMAIL, HR_EMAIL, msg.as_string())
        print(f"HR email sent to {HR_EMAIL}")
        return f"HR email successfully sent to {HR_EMAIL}"
    except Exception as e:
        print(f"Email error: {e}")
        return f"Email error: {str(e)}"


if __name__ == "__main__":
    # Test karo
    test_checklist = [
        {"task_name": "Install Node.js aur npm", "is_completed": 1},
        {"task_name": "Clone backend repository", "is_completed": 1},
        {"task_name": "Run local server", "is_completed": 0},
        {"task_name": "Read API standards document", "is_completed": 1},
        {"task_name": "Complete starter bug fix", "is_completed": 0},
    ]
    send_hr_email("Riya", "backend", "intern", "Node.js", test_checklist)
    print("Test email bheja — inbox check karo!")